In [1]:
a = 'this is a book'
a.split()

['this', 'is', 'a', 'book']

In [3]:
a = '那酸民婉君也可以報名嗎?'

In [4]:
! pip install jieba

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [6]:
import jieba
list(jieba.cut(a))

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/46/b7dzk4mn6g54qzptv608w7d00000gn/T/jieba.cache
Loading model cost 0.966 seconds.
Prefix dict has been built succesfully.


['那酸民婉君', '也', '可以', '報名', '嗎', '?']

In [8]:
article = '''
貿易戰升溫對中國經濟的衝擊可能大於美國，原因是出口對中國經濟的影響遠大於美國。經濟學家預測，如果美國祭出的關稅明年元旦升至25%，2019年中國經濟成長率將下滑0.5%至0.6個百分點。
'''

import re
re.split('，|。', article)

['\n貿易戰升溫對中國經濟的衝擊可能大於美國',
 '原因是出口對中國經濟的影響遠大於美國',
 '經濟學家預測',
 '如果美國祭出的關稅明年元旦升至25%',
 '2019年中國經濟成長率將下滑0.5%至0.6個百分點',
 '\n']

In [10]:
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=True)
#for w in seg_list:
#    print(w)
'/'.join(seg_list)

'大/巨蛋/案/對/市府/同仁/下/封口/封口令/口令////柯/P/否/認'

In [12]:
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認")
'/'.join(seg_list)

'大/巨蛋/案對/市府/同仁/下/封口令/？/\u3000/柯/P/否認'

In [16]:
import jieba
jieba.load_userdict('userdict.txt')
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認")
'/'.join(seg_list)

'大巨蛋/案對/市府/同仁/下/封口令/？/\u3000/柯P/否認'

## Jieba Zh_TW
- https://github.com/ldkrsi/jieba-zh_TW

In [17]:
import jieba.posseg as pseg
words = pseg.cut("大巨蛋案對市府同仁下封口令？　柯P否認")
for w in words:
    print(w.word, w.flag)

大巨蛋 n
案 ng
對 p
市府 n
同仁 nr
下 f
封口令 n
？ x
　 x
柯P n
否認 v


## Download Jieba
- https://pypi.org/project/jieba/#files
- https://files.pythonhosted.org/packages/71/46/c6f9179f73b818d5827202ad1c4a94e371a29473b7f043b736b4dab6b8cd/jieba-0.39.zip
- pip install ~/Downloads/jieba-0.39.zip

In [1]:
! pip install /Users/davidchiu/Downloads/jieba-0.39.zip

Processing /Users/davidchiu/Downloads/jieba-0.39.zip
  Running setup.py bdist_wheel for jieba ... done
  Stored in directory: /Users/davidchiu/Library/Caches/pip/wheels/95/48/ad/38e439c6d8ac8ff0a1a03a9ba7e9cb07d28cc408f4ff3eb20e
Successfully built jieba
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


## 取得同義詞

In [6]:
import requests
from bs4 import BeautifulSoup
res = requests.get('https://zh.wikipedia.org/wiki/{}'.format('賴清德'))
soup = BeautifulSoup(res.text, 'lxml')
soup.select_one('#bodyContent p').select('b')

[<b>賴清德</b>, <b>William Lai Ching-te</b>]

In [12]:
import requests
res = requests.get('http://ec.ltn.com.tw/article/breakingnews/2556711')

from bs4 import BeautifulSoup
soup = BeautifulSoup(res.text, 'lxml')
with open('userdict.txt', 'a') as f:
    for w in soup.select('.keyword .boxText'):
        f.write(w.text.strip()+'\n')

## 量化分析

### 詞頻

In [24]:
article = '''
周遊與老公李朝永將在10月8日補辦婚禮，前天一同出席關懷演藝人員中秋節餐會，同場的「勇伯」陳松勇卻大酸這對愛侶，周遊夫婦氣得想提告。

《聯合報》報導，陳松勇直批周遊「她厚臉皮的故事，可以寫成一本書，不是『厚黑學』，叫『厚臉皮』！」還語出驚人表示，「她現在要結婚的這個人是考古學家，每天抱著殭屍在考古。」

《壹電親》報導，周遊夫婦氣得大罵陳松勇，周遊說，「怎麼會這麼沒有水平」，「白冰冰也很生氣，替我生氣」、「我的律師說可以告他」。周遊老公李朝永不滿，說我是「考古學家」、「我覺得他這是人身攻擊」、「怎麼可以這樣子講話」、「我覺得一個人要留有口德」。（即時新聞中心／綜合報導）
'''

In [29]:
import jieba
jieba.load_userdict('userdict.txt')
words = list(jieba.cut(article))

In [31]:
dic = {}
for w in words:
    if w not in dic:
        dic[w] = 1
    else:
        dic[w] = dic[w] + 1

In [38]:
import operator
dic.items()
swd=sorted(dic.items(), key = operator.itemgetter(1), reverse=True)
for k, v in swd[0:20]:
    if len(k) >=2:
        print(k,v)

周遊 6
陳松勇 3
報導 3
可以 3
考古 3
老公 2
李朝永 2
夫婦 2
氣得 2


In [42]:
import jieba
from collections import Counter
jieba.load_userdict('userdict.txt')
words = list(jieba.cut(article))
c = Counter(words)
for k,v in c.most_common(100):
    if len(k) >=2:
        print(k,v)

周遊 6
陳松勇 3
報導 3
可以 3
考古 3
老公 2
李朝永 2
夫婦 2
氣得 2
厚臉皮 2
學家 2
怎麼 2
生氣 2
我覺 2
將在 1
10 1
補辦 1
婚禮 1
前天 1
一同 1
出席 1
關懷 1
演藝 1
人員 1
中秋節 1
餐會 1
同場 1
勇伯 1
卻大酸 1
這對 1
愛侶 1
提告 1
聯合報 1
直批 1
故事 1
寫成 1
一本 1
不是 1
黑學 1
還語 1
出驚人 1
表示 1
她現 1
結婚 1
這個 1
每天 1
抱著 1
殭屍 1
壹電親 1
這麼 1
沒有 1
水平 1
白冰冰 1
律師 1
不滿 1
這是 1
人身 1
攻擊 1
這樣子 1
講話 1
一個 1
人要 1
留有 1


In [45]:
article = '''中秋佳節烤肉幾乎已成「全民運動」，但醫界多項研究證實，食物在高溫長時間燒烤下會產生致癌物質有害健康，醫生表示，中秋過後門診常出現，大吃大喝導致血糖升高、膽固醇失控就診病人，尤其患有糖尿病、高膽固醇、腎臟病、痛風、甲狀腺亢進族群居多。

烏日林新醫院營養科姜秋月主任建議，中秋佳節烤肉、食用月餅需淺嚐即可，更別忘了要搭配高纖蔬果，吃完大餐後可與家人一起運動散步，不僅能顧到健康更能增進家人間的感情。如果在過完中秋節後，以上族群若發現身體出現不適，建議可盡快至新陳代謝科門診，以免延誤病情。（王煌忠／台中報導）

烤肉應注意五大族群
●《糖尿病族群》
中秋月餅與烤肉時搭配的吐司、白飯，充滿高糖精緻澱粉，如果沒有注意攝取份量，恐怕會造成血糖飆高！另外，糖尿病患者容易有眼睛和腎臟方面的問題，有時在戶外烤肉天色昏暗，容易吃到沒有烤熟的肉，尤其有糖尿病足的患者更要小心，烤肉時要注意不要被燙到，恐會造成傷口潰瘍惡化。

●《高膽固醇族群》
由於烤肉時會搭配烤蝦子、花枝或其他海鮮，或是油脂含量高的三層肉，甚至是食品加工物如：培根、貢丸等等，無形中都會讓膽固醇爆表！建議在食材上可均衡選擇新鮮低脂食材，如：雞胸肉、去皮的雞腿或豬里肌肉片等瘦肉。

●《腎臟病患者》
烤肉時為了讓鮮肉食材入味，會事先醃漬肉品及沾烤肉醬食用，容易產生過多鹽分，腎臟病患者在食用上要格外注意；烏日林新醫院營養科姜秋月主任表示，烤肉醬料可利用天然食材來自製DIY，選擇薑、蔥、蒜搭配奇異果等食材，就可以降低鹹度，增添自然風味。另外，蔬菜須燙過再食用，未洗腎病患須限制肉類攝取量。

●《痛風族群》
現在許多燒烤店都會提供精心熬製的雞湯或大骨湯，如果熬煮的時間越久、湯頭濃郁，代表普林的含量也很高，痛風患者最好避免！烤肉方面如果有帶殼海鮮、肉類也要注意攝取量。另外攝取糖分也會引起痛風，建議烤肉時避免喝含糖飲料、汽水或可樂，如果仍想喝飲料可以喝無糖茶飲或檸檬水。

●《甲狀腺亢進的年輕男性族群》　
烏日林新醫院新陳代謝科林瑋涵醫師表示，曾遇過甲狀腺亢進的年輕男性族群，因為平常沒有好好吃藥控制，碰到前一天晚上無節制地吃大餐，又喝太多高糖分的飲料，因受到電解質影響，早上起來竟發現自己像被鬼壓床，手腳癱軟使不上力，原來是甲狀腺毒性周期麻痺引起，好發於20～40歲的男性，必須坐救護車來醫院，為了吃得不償失。（資料來源：烏日林新醫院新陳代謝科醫師林瑋涵）

更多「 養生寶典」內容，請點此：http://bit.ly/2vrMGNZ


 


烏日林新醫院新陳代謝科醫師林瑋涵，針對五大族群患者，在中秋節烤肉應注意事項，希望民眾開心健康過中秋。翻攝畫面'''

In [48]:
import jieba
from collections import Counter
jieba.load_userdict('userdict.txt')
words = list(jieba.cut(article))
c = Counter(words)
for k,v in c.most_common(100):
    if len(k) >=2:
        print(k,v)

烤肉 13
族群 9
醫院 6
注意 6
烏日 5
林新 5
如果 5
中秋 4
膽固醇 4
痛風 4
建議 4
食用 4
搭配 4
患者 4
健康 3
表示 3
糖尿病 3
另外 3
容易 3
腎臟 3
食材 3
飲料 3
男性 3
佳節 2
運動 2
時間 2
出現 2
血糖 2
尤其 2
營養科 2
秋月 2
主任 2
大餐 2
家人 2
中秋節 2
發現 2
新陳代謝 2
五大 2
沒有 2
攝取 2
造成 2
方面 2
海鮮 2
含量 2
選擇 2
病患者 2
可以 2
肉類 2
避免 2
糖分 2
引起 2
新陳代 2
謝科 2
醫師 2


### tfidf

In [59]:
a,abb,abc = ['a'], ['a','b', 'b'], ['a', 'b', 'c'] 
D = [a,abb,abc]

In [60]:
import math
#tfidf('a', a, D)
tf  = 1/1
idf = math.log(3/3)
tf * idf 

0.0

In [61]:
import math
#tfidf('a', abb, D)
tf  = 1/3
idf = math.log(3/3)
tf * idf 

0.0

In [62]:
#tfidf('a', abc, D)
tf  = 1/3
idf = math.log(3/3)
tf * idf 

0.0

In [63]:
#tfidf('b', abb, D)
tf  = 2/3
idf = math.log(3/2)
tf * idf 

0.27031007207210955

In [64]:
#tfidf('b', abc, D)
tf  = 1/3
idf = math.log(3/2)
tf * idf 

0.13515503603605478

In [65]:
#tfidf('c', abc, D)
tf  = 1/3
idf = math.log(3/1)
tf * idf 

0.3662040962227032

In [74]:
D
ary = []
for doc in D:
    if 'c' in doc:
        ary.append(doc)
len(ary)

1

In [76]:
[doc for doc in D if 'c' in doc]

[['a', 'b', 'c']]

In [69]:
def tfidf(t, d, D):
    tf  = d.count(t) / len(d)
    idf = math.log(len(D)/ len([doc for doc in D if t in doc]))
    return tf * idf

In [70]:
tfidf('c', abc, D)

0.3662040962227032

## 詞頻矩陣

In [88]:
import jieba
jieba.load_userdict('userdict.txt')
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)))



In [89]:
corpus

['【 更新 】 柯P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 \u3000 今處理',
 '留 洪智坤   柯 ： 殘障 求職 不易',
 '人事 處議 處 洪智坤 \u3000 柯P ： 不 清楚 議處 結果']

In [90]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [91]:
print(vectorizer.get_feature_names())
X.toarray()

['不易', '人事', '今處理', '公文', '更新', '柯p', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '看到', '結果', '處議', '議處']


array([[0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [92]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(X)

array([[0.        , 3.60555128, 3.74165739],
       [3.60555128, 0.        , 3.        ],
       [3.74165739, 3.        , 0.        ]])

In [106]:
import jieba
jieba.load_userdict('userdict.txt')
synonym = {
  '柯P': '柯文哲'  
}

ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯文哲：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

corpus = []
for title in ary:
    corpus.append(' '.join([synonym.get(e, e) for e in jieba.cut(title)]))

In [107]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [108]:
print(vectorizer.get_feature_names())
X.toarray()

['不易', '人事', '今處理', '公文', '更新', '柯文哲', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '看到', '結果', '處議', '議處']


array([[0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

In [111]:
print(vectorizer.get_feature_names())
X.toarray()

['不易', '人事', '今處理', '公文', '更新', '柯文哲', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '看到', '結果', '處議', '議處']


array([[0.        , 0.        , 0.32111947, 0.64223894, 0.32111947,
        0.18965833, 0.32111947, 0.        , 0.        , 0.32111947,
        0.18965833, 0.        , 0.32111947, 0.        , 0.        ,
        0.        ],
       [0.52004008, 0.        , 0.        , 0.        , 0.        ,
        0.30714405, 0.        , 0.52004008, 0.52004008, 0.        ,
        0.30714405, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.4189401 , 0.        , 0.        , 0.        ,
        0.24743277, 0.        , 0.        , 0.        , 0.        ,
        0.24743277, 0.4189401 , 0.        , 0.4189401 , 0.4189401 ,
        0.4189401 ]])

In [118]:
ary = [
    '陳松勇酸她老公「考古學家」　周遊氣得想告',
    '''周遊與老公李朝永將在10月8日補辦婚禮，前天一同出席關懷演藝人員中秋節餐會，同場的「勇伯」陳松勇卻大酸這對愛侶，周遊夫婦氣得想提告。

《聯合報》報導，陳松勇直批周遊「她厚臉皮的故事，可以寫成一本書，不是『厚黑學』，叫『厚臉皮』！」還語出驚人表示，「她現在要結婚的這個人是考古學家，每天抱著殭屍在考古。」

《壹電親》報導，周遊夫婦氣得大罵陳松勇，周遊說，「怎麼會這麼沒有水平」，「白冰冰也很生氣，替我生氣」、「我的律師說可以告他」。周遊老公李朝永不滿，說我是「考古學家」、「我覺得他這是人身攻擊」、「怎麼可以這樣子講話」、「我覺得一個人要留有口德」。'''
]

corpus = []
for title in ary:
    corpus.append(' '.join([synonym.get(e, e) for e in jieba.cut(title)]))

In [119]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [120]:
print(vectorizer.get_feature_names())
X.toarray()

['10', '一個', '一同', '一本', '不是', '不滿', '中秋節', '人員', '人要', '人身', '出席', '出驚人', '前天', '勇伯', '卻大酸', '厚臉皮', '可以', '同場', '周遊', '報導', '壹電親', '夫婦', '她現', '婚禮', '學家', '寫成', '將在', '律師', '怎麼', '想告', '愛侶', '我覺', '抱著', '提告', '攻擊', '故事', '李朝永', '殭屍', '每天', '氣得', '水平', '沒有', '演藝', '生氣', '留有', '白冰冰', '直批', '結婚', '老公', '考古', '聯合報', '表示', '補辦', '講話', '這個', '這對', '這是', '這樣子', '這麼', '還語', '關懷', '陳松勇', '餐會', '黑學']


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 6, 2, 1, 2,
        1, 1, 2, 1, 1, 1, 2, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2,
        1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1]],
      dtype=int64)

In [121]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X)

array([[1.        , 0.55182541],
       [0.55182541, 1.        ]])

In [122]:
from sklearn.metrics.pairwise import cosine_distances
cosine_distances(X)

array([[0.        , 0.44817459],
       [0.44817459, 0.        ]])

## 文章推薦引擎

In [123]:
import pandas
news = pandas.read_excel('data/appledaily20171214.xlsx')

In [124]:
news.head()

category                                            content  \
0       政治  新增：立委說法民進黨立法院黨團預計在明天的院會中，讓改制農田水利會的《農田水利會組織通則》修...   
1       論壇  邱俊棠／台中市民、見習醫師；曾任台灣醫學生聯合會對外副會長對於公民參與公眾事務而能得到單位首...   
2       社會  被控來台涉發展情報組織的中國學生周泓旭，因接觸我方外交部官員而露餡落網，今年9月被台北地院一...   
3       生活  【廣編特輯】 對於全能神教會在中國所遭受的迫害與在韓國、香港及臺灣所面對的反面宣傳，非政府組...   
4       生活  立法院交通委員會今審查《道路交通管理處罰條例》，通過營業大客車駕駛人行駛一般道路未繫安全帶，...   

                                                link  \
0  https://tw.news.appledaily.com/politics/realti...   
1  https://tw.news.appledaily.com/forum/realtime/...   
2  https://tw.news.appledaily.com/local/realtime/...   
3  https://tw.news.appledaily.com/life/realtime/2...   
4  https://tw.news.appledaily.com/life/realtime/2...   

                            title  
0  【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲  
1               請中市府為所當為 加速中火燃煤限制  
2              陸生共諜嗆台司法　「不敢公開審理我」  
3             【特企】NGO聯名譴責中共迫害宗教信仰  
4       乘客搭大客車不配合繫安全帶　立院初審通過可罰6千元

In [125]:
corpus = []
titles = []

for rec in news.iterrows():
    corpus.append(' '.join(jieba.cut(rec[1].content) ))
    titles.append(rec[1].title)

In [127]:
#corpus[0]

In [128]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

In [129]:
X

<899x38654 sparse matrix of type '<class 'numpy.int64'>'
	with 128156 stored elements in Compressed Sparse Row format>

In [130]:
from sklearn.metrics.pairwise import cosine_distances
cs = cosine_distances(X)

In [132]:
cs.shape

(899, 899)

In [136]:
a= [80,56,70,30,90]
a.sort()
a

[30, 56, 70, 80, 90]

In [137]:
import numpy
a= numpy.array([80,56,70,30,90])
a.argsort()

array([3, 1, 2, 0, 4])

In [140]:
print(titles[0])
for idx in cs[0].argsort()[0:10]:
    if cs[0][idx] < 0.7:
        print(titles[idx], cs[0][idx])

【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲
【更新】水利會改官派明闖關　綠委24小時前顧議場大門防藍突襲 0.0
反對水利會改制　吳敦義下令：藍委做好夜宿立院抗爭準備 0.6321547504275353
農田水利會改公務機關　蔡英文：這不是綁樁 0.6724128474406619


In [175]:
def getSimilarArticle(article_id):
    print('查詢文章:',titles[article_id])
    for idx in cs[article_id].argsort()[1:10]:
        if cs[article_id][idx] < 0.75:
            print('相關文章:',titles[idx], cs[article_id][idx])

In [176]:
getSimilarArticle(42)

查詢文章: 「想抱孫要看天！」　他批小嫻婆婆殘忍強逼
相關文章: 何守正姐姐神護航！遭網友酸：全台最討人厭大姑 0.6378562180887475
相關文章: 何守正兩個姊姊護航扯婆媳　「他」戳破媽寶特色 0.6521880507152198
相關文章: 大姑出面護弟！轟小嫻不能生「媽媽是全台最沒有尊嚴的婆婆」 0.6885153247006959
相關文章: 【動畫解盤】毒菇跳火線譙seafood　小嫻難瘦香菇 0.6907806777035135
相關文章: 【毒菇護弟】何守正姊姊不是華岡七仙女　美法連線批小嫻 0.7139857980600609
相關文章: 小嫻離婚導火線　拉何守正信妙禪 0.7413065239718836


## 文章分群

In [182]:
from sklearn import cluster
km = cluster.KMeans(n_clusters=10, init='k-means++', random_state=42)
c = km.fit_predict(cs)

In [185]:
a = [1,1,2,1,3,3,2,1]

import numpy as np
na = np.array(a)
na == 1
na[na==1]

array([1, 1, 1, 1])

In [198]:
na_title = np.array(titles)
for ele in na_title[c == 2]:
    print(ele)

【好聚不好散】離婚掏出6千萬　這女星比小嫻還慘
【狗仔偷拍】小嫻搬離何守正家租66坪房　月租6萬元
許聖梅心疼小嫻被當空氣　爆何守正「有兩個女學員」
【動畫解盤】毒菇跳火線譙seafood　小嫻難瘦香菇
十二月十四日各報頭條搶先報
不捨善良小嫻慘遭婚變　乃哥「命運捉弄人」
【獨家】小嫻賣房求子　婆婆竟拒入籍何家
小嫻離婚導火線　拉何守正信妙禪
【狗仔偷拍】何守正現身！「全台最沒尊嚴的婆婆」也出來了
小嫻中分手魔咒！ 同公司4女星全都婚變
小嫻別傻傻被欺負！女律師說「姐寶」就要這樣對付
教友小嫻婚姻觸礁　曾之喬談情避不開Seafood
小嫻守正結婚在台沒登記　想離婚只有兩條路
胡瓜2個月前耳聞小嫻婚變　震驚之餘好心疼
昔日搭檔談小嫻婚變　曾國城這樣說
大姑出面護弟！轟小嫻不能生「媽媽是全台最沒有尊嚴的婆婆」
小嫻信奉妙禪　關鍵原因與何守正有關！
小嫻何守正想離婚　必須先做這件事！
「小嫻不快樂！」　許聖梅：何守正虧欠她
【內幕動畫】小嫻婚變何守正姊反擊　不滿媽煮飯侍奉星媳婦
小嫻多信妙禪？　曾見證「師父帶我跳舞」
【話當年】被拍和她上賓館　何守正掰了阿妹
小嫻婚變無徵兆　男星嘆：兩人向來出雙入對
【獨家內幕】太傷！小嫻被分手　何守正當小三面前攤牌
【小嫻離婚】何守正稱沒有遺憾　人妻女星超火「一嘴屁話」
【小嫻離婚】3大退讓人財兩失　求子花光430萬積蓄


In [202]:
(cs < 0.75).astype(int).shape

(899, 899)

In [203]:
(cs < 0.75).astype(int).sum()

3527

In [204]:
m = (cs < 0.75).astype(int)

In [205]:
m.shape

(899, 899)

In [206]:
import networkx as nx
G = nx.from_numpy_matrix(m)

In [209]:
%pylab inline
#nx.draw(G)

Populating the interactive namespace from numpy and matplotlib


## 安裝 Python Louvain
- pip install python-louvain
- https://files.pythonhosted.org/packages/c2/15/0d0e3ace40e9462ce14e0a848b3bd60c2f58296b3505b0aad75486b04cdf/python-louvain-0.11.tar.gz

In [210]:
! pip install /Users/davidchiu/Downloads/python-louvain-0.11.tar.gz

Processing /Users/davidchiu/Downloads/python-louvain-0.11.tar.gz
  Running setup.py bdist_wheel for python-louvain ... done
  Stored in directory: /Users/davidchiu/Library/Caches/pip/wheels/4f/ae/da/03a011e8d17687347738ec518290bd9bd3ba13fd7a4ab83574
Successfully built python-louvain
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [211]:
import community
comm = community.best_partition(G)

In [215]:
from collections import Counter
c = Counter(comm.values())
c.most_common(10)

[(15, 38),
 (10, 34),
 (3, 30),
 (12, 24),
 (132, 22),
 (5, 15),
 (53, 13),
 (8, 12),
 (87, 12),
 (13, 11)]

In [216]:
max(comm.values())

495

In [217]:
cluster_ary = np.array(list(comm.values()) )


In [225]:
for news in na_title[cluster_ary == 5]:
    print(news)

Fed升息美元走軟　台幣今再升破30元大關
【Fed告別秀】葉倫談比特幣　以7個字總結
Fed宣布升息1碼　台股早盤大漲逾百點
Fed升息符合預期　經濟學家：大家可過個平安聖誕節
【Fed有鴿味】美元軟了黃金硬了　美股道指創新高
這家供應商獲蘋果投資117億　股價暴漲31%
川普不給力美元軟趴趴　歐元料再升逾10%
【撈很大片】國際制裁沒有用　金正恩靠比特幣賺翻了
權威市調媒體訪客數及觸及率  《蘋果日報》全台灣第一
蘋果寫傳奇！上市37周年股價飆436倍
蘋果與台灣經濟多密切　《金融時報》這張圖表讓你秒懂
強總裁、弱台灣　央行年繳1800億造成4大後遺症
靜候FOMC結論　台幣平盤整理午盤小貶0.5分
這個國家全民瘋比特幣　政府要開緊急會議控管了
北韓高仿假鈔流入南韓　專家驚：近乎完美
